### ISSUE TITLE
"this.options" is null when mapped primitives nested in groups during set data

### ISSUE THREAD

**Issue by shahuwang** [stemey/dojo-generate-form#47]
Hi, I ran into this problem when processing this schema:
```
{
    "attributes": [
        {
            "label": "test",
            "code": "value",
            "type": "object",
            "typeProperty": "type",
            "groups": [
                {
                    "code": "test2",
                    "label": "test2",
                    "attributes": [
                        {
                            "type": "string",
                            "label": "language",
                            "values": [
                                "english",
                                "german"
                            ],
                            "code": "language"
                        },
                        {
                            "type": "string",
                            "label": "salutation",
                            "mapped_attribute": "language",
                            "mapped_values": {
                                "english": [
                                    "Mr.",
                                    "Mrs."
                                ],
                                "german": [
                                    "Herr",
                                    "Frau"
                                ]
                            },
                            "code": "salutation"
                        }
                    ]
                }
            ]
        }
    ]
}
```
it is ok to create an editor with this schema, but when I want to set PlainValue:
var data = {"value":{"language":"german", "salutation":"Frau", "type":"test2"}};
editor.setMetaAndPlainValue(schema,data);

I got an error:
TypeError: Cannot read property 'length' of null {stack: (...), message: "Cannot read property 'length' of null"}message: "Cannot read property 'length' of null"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: Error "TypeError: Cannot read property 'length' of null

I don't know why this happened, wish to be fixed quickly, thanks!

**Comment by stemey** [comment]
I wasn not able to reproduce your problem. I created a jsfiddle. Please go ahead and change it to create the error:

http://jsfiddle.net/z0fgovwj/2/

**Comment by shahuwang** [comment]
Hi, I found that this error only happens when using editor.setMetaAndPlainValue(schema,data);

**Comment by stemey** [comment]
Still cannot reproduce the error:

http://jsfiddle.net/z0fgovwj/4/

**Comment by shahuwang** [comment]
Thanks, it seems that in the new version this bug has been fixed .
We use an old version as gform API has changed so much (https://github.com/ejoy/dojo-generate-form)[https://github.com/ejoy/dojo-generate-form],

(http://jsfiddle.net/z0fgovwj/3/)[http://jsfiddle.net/z0fgovwj/3/]

**Comment by shahuwang** [comment]
Hi, I produced another err with this schema, just change the meta schema, and setMetaAndPlainValue twice

http://jsfiddle.net/z0fgovwj/7/

**Comment by stemey** [comment]
Actually I used rawgit/master and that quickly leads to errors because the traffic is too high. Now moved to 0.22.2 (an older version).

http://jsfiddle.net/z0fgovwj/9/

**Comment by stemey** [comment]
Here is the explanation : https://rawgit.com/

**Comment by stemey** [comment]
Why don't you just tag your branch and then edit the jsfiddle options "framework" accordingly:

data-dojo-config="isDebug: true, async: true, parseOnLoad: true,packages:[{name:'gform', location:'https://rawgit.com/stemey/dojo-generate-form/0.22.2/'}]"

**Comment by shahuwang** [comment]
Sorry to trouble you.
Now I try the newest version gform, and the issue  "Cannot read property 'length' of null" is solved ( I void this error by setting meta and Plainvalue apart in my fork version).
But then I found another error, both in my fork version and the newest master version.
http://jsfiddle.net/z0fgovwj/15/

The error message is "TypeError: Cannot read property 'style' of null"

**Comment by stemey** [comment]
That is a definitely a bug. A zombie widget is still listening to events. Will have a look at it.
