### ISSUE TITLE
Unable to use registerStandardEditorFactory

### ISSUE THREAD

**Issue by gokhalep** [stemey/dojo-generate-form#48]
Hello,
I'm trying to setup and play with gform. Getting an error "ReferenceError: define is not defined
dojo._loadUriAndCheck()". 
This is while loading the editorFactory module at dojo.require("gform/registerStandardEditorFactory"); 

The firedebug console has following:
failed loading ../../../../dojo/dojo/../gform/registerStandardEditorFactory.js with error: ReferenceError: define is not defined
dojo._loadUriAndCheck()dojo.js (line 14)
dojo._loadPath(_21="../gform/registerStandardEditorFactory.js", _22="gform/registerStandardEditorFactory", cb=undefined)dojo.js (line 14)
dojo.require(_2d="gform/registerStandardEditorFactory", _2e=undefined)dojo.js (line 14)
FullGenDialog.html()

**Comment by stemey** [comment]
I setup a simple project: https://github.com/stemey/gform-playground. That should help you.

**Comment by gokhalep** [comment]
Thanks, that helped resolve sort out dependencies. Can you please confirm what's the minimum dojo version required to use gform?

**Comment by stemey** [comment]
I am using 1.9.2. I have not run the tests with older versions.
