### ISSUE TITLE
type integer group element form need to switch twitce to show up 

### ISSUE THREAD

**Issue by muzuiget** [stemey/dojo-generate-form#53]
```
var schema = {
    attributes: [
        {
            code: 'triggerTypeGroup',
            type: 'object',
            typeProperty: 'triggerType',
            required: true,
            groups: [
                {
                    code: 'date1',
                    attributes: [
                        {
                            code: 'run_date',
                            type: 'string',
                            placeHolder: 'type is string',
                            required: true,
                        }
                    ],
                },
                {
                    code: 'date2',
                    attributes: [
                        {
                            code: 'run_date',
                            type: 'integer',
                            placeHolder: 'type is integer',
                            required: true,
                        }
                    ],
                },
            ]
        }
    ]
};
```

Similar to #52, when `date2` group element has a `integer` type, need to switch twice to make the form show up, but use `number` type if fine.

**Comment by stemey** [comment]
there is actually no 'integer' type. What you probably want is a number without decimal digits:

        {
 	 code: 'run_date',
	 type: 'number',
	 placeHolder: 'type is integer',
	 required: true,
	 places:0
      }

**Comment by muzuiget** [comment]
What I actually want I don't the input widget display the number separator by comma, for example, the address port `8,080`, of course I can use `numberFormat`, but I think the pattern of `numberFormat` is a bit complex and not semantic, I prefer disable separator-by-comma disabled by default.

**Comment by stemey** [comment]
You can create your own AttributeFactory and register it with your EditorFactory. You might not want to use NumberTextbox but Textbox, so that you avoid formatting completely. 

To create an Attributefactory with your defaults based on NumberTextbox you can do the following:

        return declare([NumberAttributeFactory],
            {
                id: "integer",
                handles: function (attribute) {
                    return meta.isType(attribute, "integer");
                },
                create: function (attribute, modelHandle) {
                        var widget = this.inherited(arguments);
                        widget.set("places",0);
                        widget.set("numberFormat","########################"); 
                       return widget
         }}
